import { runFfmpeg } from "./spawn.js";
import { probe, audioStream } from "./ffprobe.js";
import { resolveExistingAssetPath } from "../util/assetRoot.js";
import { timelineAudioClips } from "../render/media.js";
import type { EditPlan } from "../schema/editPlan.js";

/**
 * Deterministic audio assembly and mux.
 *
 * Two paths:
 *  - When a plan declares no external audio (no dialogue, no music, no SFX), the
 *    demo bed is a fully procedural tone bed generated by FFmpeg's lavfi sources,
 *    normalized to the plan's loudness target. No file is read from disk.
 *  - When a plan declares any real audio, those files are resolved under the
 *    asset root and mixed with a clear hierarchy (dialogue over SFX over the
 *    music bed), delayed to their cue times, resampled to stereo 48 kHz, and
 *    loudness-normalized to the plan target. Every call uses argument arrays.
 */

// Relative mix levels. Absolute values do not matter after loudnorm; the
// ordering is the editorial hierarchy: dialogue reads over SFX over the bed.
const DIALOGUE_VOLUME = 1.0;
const SFX_VOLUME = 0.6;
const MUSIC_VOLUME = 0.18;

const STEREO_48K = "aresample=48000,aformat=sample_fmts=fltp:channel_layouts=stereo";

export interface ResolvedAudio {
  dialogue?: string;
  music?: string;
  sfx: Array<{ abs: string; timeMs: number; durationSeconds?: number }>;
}

/** True when the plan asks for any real, on-disk audio. */
export function declaresExternalAudio(plan: EditPlan): boolean {
  return Boolean(plan.audio.dialoguePath) || Boolean(plan.audio.music) || plan.audio.sfx.length > 0;
}

/** Resolve every declared audio file under the asset root (throws if missing). */
export function resolveAudio(plan: EditPlan): ResolvedAudio {
  const resolved: ResolvedAudio = { sfx: [] };
  if (plan.audio.dialoguePath) {
    resolved.dialogue = resolveExistingAssetPath(plan.audio.dialoguePath, "dialogue track");
  }
  if (plan.audio.music) {
    resolved.music = resolveExistingAssetPath(plan.audio.music.path, "music track");
  }
  for (const cue of plan.audio.sfx) {
    resolved.sfx.push({
      abs: resolveExistingAssetPath(cue.asset, `sfx asset '${cue.asset}'`),
      timeMs: Math.round(cue.time * 1000),
      durationSeconds: cue.duration,
    });
  }
  return resolved;
}

/**
 * Build the FFmpeg argument array for a real audio timeline. A silent base of
 * exactly `duration` seconds pins the length; dialogue, a looped music bed, and
 * time-delayed SFX are mixed onto it, then loudness-normalized to the target.
 */
export function buildAudioAssemblyArgs(
  plan: EditPlan,
  duration: number,
  resolved: ResolvedAudio,
  outPath = "audio.wav",
): string[] {
  const d = duration.toFixed(3);
  const target = plan.audio.targetLufs;
  const tp = plan.audio.truePeakDb;

  const inputs: string[] = ["-f", "lavfi", "-t", d, "-i", "anullsrc=r=48000:cl=stereo"];
  const filters: string[] = ["[0:a]aformat=sample_fmts=fltp:channel_layouts=stereo[base]"];
  const mixLabels: string[] = ["[base]"];
  let idx = 1;

  if (resolved.dialogue) {
    inputs.push("-i", resolved.dialogue);
    filters.push(`[${idx}:a]${STEREO_48K},volume=${DIALOGUE_VOLUME}[dia]`);
    mixLabels.push("[dia]");
    idx++;
  }
  if (resolved.music) {
    // Loop the licensed bed so it covers the whole timeline; the amix duration
    // is pinned to the base, so any extra loop tail is discarded.
    inputs.push("-stream_loop", "-1", "-i", resolved.music);
    filters.push(`[${idx}:a]${STEREO_48K},volume=${MUSIC_VOLUME}[mus]`);
    mixLabels.push("[mus]");
    idx++;
  }
  resolved.sfx.forEach((cue, k) => {
    inputs.push("-i", cue.abs);
    const trim = cue.durationSeconds === undefined
      ? ""
      : `,atrim=duration=${cue.durationSeconds.toFixed(3)},asetpts=PTS-STARTPTS`;
    filters.push(`[${idx}:a]${STEREO_48K},volume=${SFX_VOLUME}${trim},adelay=${cue.timeMs}|${cue.timeMs}[sfx${k}]`);
    mixLabels.push(`[sfx${k}]`);
    idx++;
  });

  filters.push(
    `${mixLabels.join("")}amix=inputs=${mixLabels.length}:normalize=0:duration=first[mix]`,
  );
  filters.push(`[mix]loudnorm=I=${target}:TP=${tp}:LRA=11[out]`);

  return [
    ...inputs,
    "-filter_complex",
    filters.join(";"),
    "-map",
    "[out]",
    "-ac",
    "2",
    "-ar",
    "48000",
    "-t",
    d,
    "-c:a",
    "pcm_s16le",
    "-y",
    outPath,
  ];
}

/** A timeline audio clip resolved to an absolute file and its placement in the final mix. */
export interface ResolvedTimelineAudioClip {
  abs: string;
  /** Timeline start delay, milliseconds. */
  startMs: number;
  /** Trim in-point into the source media, seconds. */
  sourceIn: number;
  /** Length taken from the source, seconds. */
  duration: number;
  /** 0..1 clip gain (muted tracks are already excluded upstream). */
  volume: number;
}

/**
 * Build the FFmpeg argument array for a timeline's audio. A silent base of exactly `duration`
 * seconds pins the length; each clip is trimmed to its source in-point and timeline duration,
 * resampled to stereo 48 kHz, gained by its clip volume, delayed to its timeline start, then
 * mixed onto the base and loudness-normalized to the plan target. The visual master is rendered
 * muted, so this is the single audio source (no double audio).
 */
export function buildTimelineAudioArgs(
  plan: EditPlan,
  duration: number,
  clips: ResolvedTimelineAudioClip[],
  outPath = "audio.wav",
): string[] {
  const d = duration.toFixed(3);
  const target = plan.audio.targetLufs;
  const tp = plan.audio.truePeakDb;

  const inputs: string[] = ["-f", "lavfi", "-t", d, "-i", "anullsrc=r=48000:cl=stereo"];
  const filters: string[] = ["[0:a]aformat=sample_fmts=fltp:channel_layouts=stereo[base]"];
  const mixLabels: string[] = ["[base]"];
  let idx = 1;

  clips.forEach((clip, k) => {
    inputs.push("-i", clip.abs);
    const start = clip.sourceIn.toFixed(3);
    const end = (clip.sourceIn + clip.duration).toFixed(3);
    filters.push(
      `[${idx}:a]atrim=start=${start}:end=${end},asetpts=PTS-STARTPTS,${STEREO_48K},volume=${clip.volume},adelay=${clip.startMs}|${clip.startMs}[c${k}]`,
    );
    mixLabels.push(`[c${k}]`);
    idx++;
  });

  filters.push(`${mixLabels.join("")}amix=inputs=${mixLabels.length}:normalize=0:duration=first[mix]`);
  filters.push(`[mix]loudnorm=I=${target}:TP=${tp}:LRA=11[out]`);

  return [
    ...inputs,
    "-filter_complex",
    filters.join(";"),
    "-map",
    "[out]",
    "-ac",
    "2",
    "-ar",
    "48000",
    "-t",
    d,
    "-c:a",
    "pcm_s16le",
    "-y",
    outPath,
  ];
}

/**
 * Resolve every audio-bearing timeline clip under the asset root and keep only those whose
 * source actually carries an audio stream (a silent video clip contributes nothing to the mix).
 * Muted tracks and zero-volume clips are already dropped by `timelineAudioClips`.
 */
export async function resolveTimelineAudio(plan: EditPlan): Promise<ResolvedTimelineAudioClip[]> {
  const out: ResolvedTimelineAudioClip[] = [];
  for (const clip of timelineAudioClips(plan)) {
    const abs = resolveExistingAssetPath(clip.path, `timeline audio clip '${clip.id}'`);
    const probed = await probe(abs);
    if (!audioStream(probed)) continue;
    out.push({ abs, startMs: Math.round(clip.start * 1000), sourceIn: clip.sourceIn, duration: clip.duration, volume: clip.volume });
  }
  return out;
}

/**
 * Assemble the plan's audio to `outWav`. When the plan carries a timeline, the audio is built
 * from its video/audio clips (start, trim, volume, muted tracks); if none of them contribute
 * audio, the procedural bed keeps QA's loudness contract satisfied. When there is no timeline,
 * the legacy behavior is unchanged: real declared files are mixed, else the procedural bed.
 */
export async function assembleAudio(
  plan: EditPlan,
  duration: number,
  outWav: string,
): Promise<void> {
  if (plan.timeline) {
    const clips = await resolveTimelineAudio(plan);
    if (clips.length === 0) {
      await buildProceduralBed(plan, duration, outWav);
      return;
    }
    const res = await runFfmpeg(buildTimelineAudioArgs(plan, duration, clips, outWav));
    if (res.code !== 0) {
      throw new Error(`Timeline audio assembly failed: ${res.stderr.trim().slice(0, 400)}`);
    }
    return;
  }
  if (!declaresExternalAudio(plan)) {
    await buildProceduralBed(plan, duration, outWav);
    return;
  }
  const resolved = resolveAudio(plan);
  const res = await runFfmpeg(buildAudioAssemblyArgs(plan, duration, resolved, outWav));
  if (res.code !== 0) {
    throw new Error(`Audio assembly failed: ${res.stderr.trim().slice(0, 400)}`);
  }
}

/** Generate a procedural, loudness-normalized stereo WAV bed of `duration` s. */
export async function buildProceduralBed(
  plan: EditPlan,
  duration: number,
  outWav: string,
): Promise<void> {
  const d = duration.toFixed(3);
  const target = plan.audio.targetLufs;
  const tp = plan.audio.truePeakDb;
  // Two sine partials a perfect fifth apart, gentle tremolo, then EBU normalize.
  const filter =
    `[0:a]volume=0.5[a0];` +
    `[1:a]volume=0.32[a1];` +
    `[a0][a1]amix=inputs=2:normalize=0[m];` +
    `[m]tremolo=f=1.8:d=0.35,loudnorm=I=${target}:TP=${tp}:LRA=11[out]`;

  const res = await runFfmpeg([
    "-f", "lavfi", "-i", `sine=frequency=110:sample_rate=48000:duration=${d}`,
    "-f", "lavfi", "-i", `sine=frequency=164.814:sample_rate=48000:duration=${d}`,
    "-filter_complex", filter,
    "-map", "[out]",
    "-ac", "2",
    "-ar", "48000",
    "-t", d,
    "-c:a", "pcm_s16le",
    "-y", outWav,
  ]);
  if (res.code !== 0) {
    throw new Error(`Procedural bed generation failed: ${res.stderr.trim().slice(0, 400)}`);
  }
}

/**
 * Build the mux argument array. The silent video is copied at full length and
 * the assembled audio is attached. No `-shortest`: instead an explicit `-t`
 * equal to the rendered visual duration keeps the complete visual tail while
 * trimming any audio overrun. Inherited metadata is stripped.
 */
export function buildMuxArgs(
  plan: EditPlan,
  videoPath: string,
  audioPath: string,
  outPath: string,
  durationSeconds: number,
): string[] {
  const args = [
    "-i", videoPath,
    "-i", audioPath,
    "-map", "0:v:0",
    "-map", "1:a:0",
    "-c:v", "copy",
    "-c:a", plan.output.audioCodec,
    "-b:a", plan.output.audioBitrate,
    "-ar", "48000",
    "-t", durationSeconds.toFixed(3),
  ];
  if (plan.output.stripMetadata) {
    args.push("-map_metadata", "-1", "-map_metadata:s", "-1");
  }
  if (plan.output.faststart) {
    args.push("-movflags", "+faststart");
  }
  args.push("-y", outPath);
  return args;
}

/**
 * Mux a silent video master with an audio track into the delivered final master.
 * Strips all inherited metadata, encodes AAC 48 kHz, and enables faststart.
 */
export async function muxFinalMaster(
  plan: EditPlan,
  videoPath: string,
  audioPath: string,
  outPath: string,
  durationSeconds: number,
): Promise<void> {
  const res = await runFfmpeg(buildMuxArgs(plan, videoPath, audioPath, outPath, durationSeconds));
  if (res.code !== 0) {
    throw new Error(`Final mux failed: ${res.stderr.trim().slice(0, 400)}`);
  }
}
